// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AnswerEvaluateRequest
 *
 * 回答评估请求
 */
export type AnswerEvaluateRequest = {
    /**
     * Question
     *
     * 面试问题
     */
    question: string;
    /**
     * Answer
     *
     * 候选人回答
     */
    answer: string;
    /**
     * Target Skills
     *
     * 目标技能
     */
    target_skills?: Array<string> | null;
    /**
     * Difficulty
     *
     * 问题难度
     */
    difficulty?: number;
};

/**
 * ApplicationCreate
 *
 * 创建应聘申请请求
 */
export type ApplicationCreate = {
    /**
     * Position Id
     *
     * 岗位ID
     */
    position_id: string;
    /**
     * Resume Id
     *
     * 简历ID
     */
    resume_id: string;
    /**
     * Notes
     *
     * 备注
     */
    notes?: string | null;
};

/**
 * ApplicationDetailResponse
 *
 * 应聘申请详情响应（包含关联数据）
 */
export type ApplicationDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Position Id
     */
    position_id: string;
    /**
     * Resume Id
     */
    resume_id: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    position?: PositionListResponse | null;
    resume?: ResumeListResponse | null;
    /**
     * Screening Tasks
     */
    screening_tasks?: Array<ScreeningTaskBrief>;
    /**
     * Video Analyses
     */
    video_analyses?: Array<VideoAnalysisBrief>;
    /**
     * Interview Sessions
     */
    interview_sessions?: Array<InterviewSessionBrief>;
    /**
     * Comprehensive Analyses
     */
    comprehensive_analyses?: Array<ComprehensiveAnalysisBrief>;
};

/**
 * ApplicationListResponse
 *
 * 应聘申请列表项响应
 */
export type ApplicationListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Position Id
     */
    position_id: string;
    /**
     * Resume Id
     */
    resume_id: string;
    /**
     * Position Title
     */
    position_title?: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
};

/**
 * ApplicationResponse
 *
 * 应聘申请响应
 */
export type ApplicationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Position Id
     */
    position_id: string;
    /**
     * Resume Id
     */
    resume_id: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
};

/**
 * ApplicationUpdate
 *
 * 更新应聘申请请求
 */
export type ApplicationUpdate = {
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * BatchDeleteData
 *
 * 批量删除结果
 */
export type BatchDeleteData = {
    /**
     * Deleted Count
     */
    deleted_count: number;
    /**
     * Requested Count
     */
    requested_count: number;
};

/**
 * BatchDeleteRequest
 *
 * 批量删除请求
 */
export type BatchDeleteRequest = {
    /**
     * Resume Ids
     *
     * 简历ID列表
     */
    resume_ids: Array<string>;
};

/**
 * BatchHashCheckData
 *
 * 批量哈希检查结果
 */
export type BatchHashCheckData = {
    /**
     * Exists
     */
    exists: {
        [key: string]: boolean;
    };
    /**
     * Existing Count
     */
    existing_count: number;
};

/**
 * BigFiveScores
 *
 * 大五人格评分
 */
export type BigFiveScores = {
    /**
     * Openness
     *
     * 开放性
     */
    openness?: number | null;
    /**
     * Conscientiousness
     *
     * 尽责性
     */
    conscientiousness?: number | null;
    /**
     * Extraversion
     *
     * 外向性
     */
    extraversion?: number | null;
    /**
     * Agreeableness
     *
     * 宜人性
     */
    agreeableness?: number | null;
    /**
     * Neuroticism
     *
     * 神经质
     */
    neuroticism?: number | null;
};

/**
 * CandidateQuestionsRequest
 *
 * 候选问题生成请求
 */
export type CandidateQuestionsRequest = {
    /**
     * Current Question
     *
     * 当前问题
     */
    current_question: string;
    /**
     * Current Answer
     *
     * 当前回答
     */
    current_answer: string;
    /**
     * Conversation History
     *
     * 历史对话
     */
    conversation_history?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Resume Summary
     *
     * 简历摘要
     */
    resume_summary?: string | null;
    /**
     * Followup Count
     *
     * 追问数量
     */
    followup_count?: number;
    /**
     * Alternative Count
     *
     * 候选问题数量
     */
    alternative_count?: number;
};

/**
 * CheckHashesRequest
 *
 * 批量哈希检查请求
 */
export type CheckHashesRequest = {
    /**
     * Hashes
     *
     * 哈希值列表
     */
    hashes: Array<string>;
};

/**
 * ComprehensiveAnalysisBrief
 *
 * 综合分析简要信息
 */
export type ComprehensiveAnalysisBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Final Score
     */
    final_score: number;
    /**
     * Recommendation Level
     */
    recommendation_level: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ComprehensiveAnalysisCreate
 *
 * 创建综合分析请求
 */
export type ComprehensiveAnalysisCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ComprehensiveAnalysisRequest
 *
 * 综合分析请求
 */
export type ComprehensiveAnalysisRequest = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ComprehensiveAnalysisResponse
 *
 * 综合分析响应
 */
export type ComprehensiveAnalysisResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Final Score
     */
    final_score: number;
    /**
     * Recommendation Level
     */
    recommendation_level: string;
    /**
     * Recommendation Reason
     */
    recommendation_reason: string | null;
    /**
     * Suggested Action
     */
    suggested_action: string | null;
    /**
     * Dimension Scores
     */
    dimension_scores: {
        [key: string]: unknown;
    };
    /**
     * Report
     */
    report: string | null;
    /**
     * Input Snapshot
     */
    input_snapshot: {
        [key: string]: unknown;
    };
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * DictResponse
 *
 * 字典数据响应
 */
export type DictResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * FinalReportRequest
 *
 * 最终报告生成请求
 */
export type FinalReportRequest = {
    /**
     * Session Id
     *
     * 面试会话ID
     */
    session_id: string;
    /**
     * Hr Notes
     *
     * HR备注
     */
    hr_notes?: string | null;
};

/**
 * GenerateQuestionsRequest
 *
 * 生成问题请求
 */
export type GenerateQuestionsRequest = {
    /**
     * Count
     *
     * 生成问题数量
     */
    count?: number;
    /**
     * Difficulty
     *
     * 难度: easy/medium/hard
     */
    difficulty?: string;
    /**
     * Focus Areas
     *
     * 关注领域
     */
    focus_areas?: Array<string> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HashCheckData
 *
 * 哈希检查结果
 */
export type HashCheckData = {
    /**
     * Exists
     */
    exists: boolean;
};

/**
 * InterviewQuestionsRequest
 *
 * 面试问题生成请求
 */
export type InterviewQuestionsRequest = {
    /**
     * Session Id
     *
     * 面试会话ID
     */
    session_id: string;
    /**
     * Resume Content
     *
     * 简历内容
     */
    resume_content?: string | null;
    /**
     * Count
     *
     * 问题数量
     */
    count?: number;
    /**
     * Interest Point Count
     *
     * 兴趣点数量
     */
    interest_point_count?: number;
};

/**
 * InterviewSessionBrief
 *
 * 面试会话简要信息
 */
export type InterviewSessionBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Interview Type
     */
    interview_type: string;
    /**
     * Is Completed
     */
    is_completed: boolean;
    /**
     * Final Score
     */
    final_score: number | null;
    /**
     * Current Round
     */
    current_round?: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * InterviewSessionCreate
 *
 * 创建面试会话请求
 */
export type InterviewSessionCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
    /**
     * Interview Type
     *
     * 面试类型
     */
    interview_type?: string;
    /**
     * Config
     *
     * 面试配置
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * InterviewSessionResponse
 *
 * 面试会话响应
 */
export type InterviewSessionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Interview Type
     */
    interview_type: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Qa Records
     */
    qa_records: Array<QaRecord>;
    /**
     * Question Pool
     */
    question_pool: Array<string>;
    /**
     * Is Completed
     */
    is_completed: boolean;
    /**
     * Final Score
     */
    final_score: number | null;
    /**
     * Report
     */
    report: {
        [key: string]: unknown;
    } | null;
    /**
     * Report Markdown
     */
    report_markdown: string | null;
    /**
     * Current Round
     */
    current_round?: number;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * MessageResponse
 *
 * 仅消息响应（无数据）
 */
export type MessageResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    /**
     * Data
     */
    data?: null;
};

/**
 * PagedData[ApplicationListResponse]
 */
export type PagedDataApplicationListResponse = {
    /**
     * Items
     */
    items: Array<ApplicationListResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ComprehensiveAnalysisResponse]
 */
export type PagedDataComprehensiveAnalysisResponse = {
    /**
     * Items
     */
    items: Array<ComprehensiveAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[InterviewSessionResponse]
 */
export type PagedDataInterviewSessionResponseInput = {
    /**
     * Items
     */
    items: Array<InterviewSessionResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[InterviewSessionResponse]
 */
export type PagedDataInterviewSessionResponseOutput = {
    /**
     * Items
     */
    items: Array<InterviewSessionResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[PositionListResponse]
 */
export type PagedDataPositionListResponse = {
    /**
     * Items
     */
    items: Array<PositionListResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ResumeListResponse]
 */
export type PagedDataResumeListResponse = {
    /**
     * Items
     */
    items: Array<ResumeListResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ScreeningTaskResponse]
 */
export type PagedDataScreeningTaskResponse = {
    /**
     * Items
     */
    items: Array<ScreeningTaskResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[VideoAnalysisResponse]
 */
export type PagedDataVideoAnalysisResponseInput = {
    /**
     * Items
     */
    items: Array<VideoAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[VideoAnalysisResponse]
 */
export type PagedDataVideoAnalysisResponseOutput = {
    /**
     * Items
     */
    items: Array<VideoAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedResponseModel[ApplicationListResponse]
 */
export type PagedResponseModelApplicationListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataApplicationListResponse;
};

/**
 * PagedResponseModel[ComprehensiveAnalysisResponse]
 */
export type PagedResponseModelComprehensiveAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataComprehensiveAnalysisResponse;
};

/**
 * PagedResponseModel[InterviewSessionResponse]
 */
export type PagedResponseModelInterviewSessionResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataInterviewSessionResponseOutput;
};

/**
 * PagedResponseModel[PositionListResponse]
 */
export type PagedResponseModelPositionListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataPositionListResponse;
};

/**
 * PagedResponseModel[ResumeListResponse]
 */
export type PagedResponseModelResumeListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataResumeListResponse;
};

/**
 * PagedResponseModel[ScreeningTaskResponse]
 */
export type PagedResponseModelScreeningTaskResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataScreeningTaskResponse;
};

/**
 * PagedResponseModel[VideoAnalysisResponse]
 */
export type PagedResponseModelVideoAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataVideoAnalysisResponseOutput;
};

/**
 * PositionCreate
 *
 * 创建岗位请求
 */
export type PositionCreate = {
    /**
     * Title
     *
     * 岗位名称
     */
    title: string;
    /**
     * Department
     *
     * 所属部门
     */
    department?: string | null;
    /**
     * Description
     *
     * 岗位描述/JD
     */
    description?: string | null;
    /**
     * Required Skills
     *
     * 必备技能
     */
    required_skills?: Array<string> | null;
    /**
     * Optional Skills
     *
     * 可选技能
     */
    optional_skills?: Array<string> | null;
    /**
     * Min Experience
     *
     * 最低工作年限
     */
    min_experience?: number;
    /**
     * Education
     *
     * 学历要求
     */
    education?: Array<string> | null;
    /**
     * Salary Min
     *
     * 最低薪资(K)
     */
    salary_min?: number;
    /**
     * Salary Max
     *
     * 最高薪资(K)
     */
    salary_max?: number;
};

/**
 * PositionGenerateRequest
 *
 * 岗位需求生成请求
 */
export type PositionGenerateRequest = {
    /**
     * Description
     *
     * 岗位描述（一句话或详细说明）
     */
    description: string;
    /**
     * Documents
     *
     * 参考文档列表
     */
    documents?: Array<{
        [key: string]: string;
    }> | null;
};

/**
 * PositionListResponse
 *
 * 岗位列表项响应（简化版）
 */
export type PositionListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Title
     */
    title: string;
    /**
     * Department
     */
    department: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Application Count
     */
    application_count?: number;
};

/**
 * PositionResponse
 *
 * 岗位响应
 */
export type PositionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Title
     */
    title: string;
    /**
     * Department
     */
    department: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Required Skills
     */
    required_skills: Array<string>;
    /**
     * Optional Skills
     */
    optional_skills: Array<string>;
    /**
     * Min Experience
     */
    min_experience: number;
    /**
     * Education
     */
    education: Array<string>;
    /**
     * Salary Min
     */
    salary_min: number;
    /**
     * Salary Max
     */
    salary_max: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Application Count
     *
     * 申请数量
     */
    application_count?: number;
};

/**
 * PositionUpdate
 *
 * 更新岗位请求
 */
export type PositionUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Required Skills
     */
    required_skills?: Array<string> | null;
    /**
     * Optional Skills
     */
    optional_skills?: Array<string> | null;
    /**
     * Min Experience
     */
    min_experience?: number | null;
    /**
     * Education
     */
    education?: Array<string> | null;
    /**
     * Salary Min
     */
    salary_min?: number | null;
    /**
     * Salary Max
     */
    salary_max?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * QARecord
 *
 * 问答记录
 */
export type QaRecord = {
    /**
     * Round
     *
     * 轮次
     */
    round: number;
    /**
     * Question
     *
     * 问题
     */
    question: string;
    /**
     * Answer
     *
     * 回答
     */
    answer: string;
    /**
     * Score
     *
     * 评分
     */
    score?: number | null;
    /**
     * Evaluation
     *
     * 评价
     */
    evaluation?: string | null;
};

/**
 * QARecordCreate
 *
 * 添加问答记录请求
 */
export type QaRecordCreate = {
    /**
     * Question
     *
     * 问题
     */
    question: string;
    /**
     * Answer
     *
     * 回答
     */
    answer: string;
    /**
     * Score
     *
     * 评分
     */
    score?: number | null;
    /**
     * Evaluation
     *
     * 评价
     */
    evaluation?: string | null;
};

/**
 * RandomResumeRequest
 *
 * 随机简历生成请求
 */
export type RandomResumeRequest = {
    /**
     * Position Id
     *
     * 岗位ID
     */
    position_id: string;
    /**
     * Count
     *
     * 生成数量
     */
    count?: number;
};

/**
 * ResponseModel[ApplicationDetailResponse]
 */
export type ResponseModelApplicationDetailResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ApplicationDetailResponse | null;
};

/**
 * ResponseModel[ApplicationResponse]
 */
export type ResponseModelApplicationResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ApplicationResponse | null;
};

/**
 * ResponseModel[BatchDeleteData]
 */
export type ResponseModelBatchDeleteData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: BatchDeleteData | null;
};

/**
 * ResponseModel[BatchHashCheckData]
 */
export type ResponseModelBatchHashCheckData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: BatchHashCheckData | null;
};

/**
 * ResponseModel[ComprehensiveAnalysisResponse]
 */
export type ResponseModelComprehensiveAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ComprehensiveAnalysisResponse | null;
};

/**
 * ResponseModel[HashCheckData]
 */
export type ResponseModelHashCheckData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: HashCheckData | null;
};

/**
 * ResponseModel[InterviewSessionResponse]
 */
export type ResponseModelInterviewSessionResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: InterviewSessionResponse | null;
};

/**
 * ResponseModel[PositionResponse]
 */
export type ResponseModelPositionResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: PositionResponse | null;
};

/**
 * ResponseModel[ResumeResponse]
 */
export type ResponseModelResumeResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ResumeResponse | null;
};

/**
 * ResponseModel[ScreeningTaskResponse]
 */
export type ResponseModelScreeningTaskResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ScreeningTaskResponse | null;
};

/**
 * ResponseModel[VideoAnalysisResponse]
 */
export type ResponseModelVideoAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: VideoAnalysisResponse | null;
};

/**
 * ResumeCreate
 *
 * 创建简历请求
 */
export type ResumeCreate = {
    /**
     * Candidate Name
     *
     * 候选人姓名
     */
    candidate_name: string;
    /**
     * Phone
     *
     * 联系电话
     */
    phone?: string | null;
    /**
     * Email
     *
     * 电子邮箱
     */
    email?: string | null;
    /**
     * Content
     *
     * 简历内容
     */
    content: string;
    /**
     * Filename
     *
     * 原始文件名
     */
    filename?: string | null;
    /**
     * Notes
     *
     * 备注
     */
    notes?: string | null;
    /**
     * File Hash
     *
     * 文件哈希
     */
    file_hash: string;
    /**
     * File Size
     *
     * 文件大小
     */
    file_size?: number;
};

/**
 * ResumeListResponse
 *
 * 简历列表项响应（简化版）
 */
export type ResumeListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Candidate Name
     */
    candidate_name: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * Is Parsed
     */
    is_parsed: boolean;
    /**
     * Application Count
     */
    application_count?: number;
};

/**
 * ResumeResponse
 *
 * 简历响应
 */
export type ResumeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Candidate Name
     */
    candidate_name: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * File Hash
     */
    file_hash: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Is Parsed
     */
    is_parsed: boolean;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Application Count
     *
     * 申请数量
     */
    application_count?: number;
};

/**
 * ResumeUpdate
 *
 * 更新简历请求
 */
export type ResumeUpdate = {
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Parsed
     */
    is_parsed?: boolean | null;
};

/**
 * ScreeningResultUpdate
 *
 * 更新筛选结果请求
 */
export type ScreeningResultUpdate = {
    /**
     * Status
     *
     * 任务状态
     */
    status?: string | null;
    /**
     * Progress
     *
     * 进度
     */
    progress?: number | null;
    /**
     * Score
     *
     * 综合评分
     */
    score?: number | null;
    /**
     * Dimension Scores
     *
     * 各维度评分
     */
    dimension_scores?: {
        [key: string]: unknown;
    } | null;
    /**
     * Summary
     *
     * 筛选总结
     */
    summary?: string | null;
    /**
     * Recommendation
     *
     * 推荐结果
     */
    recommendation?: string | null;
    /**
     * Report Content
     *
     * 报告内容
     */
    report_content?: string | null;
    /**
     * Error Message
     *
     * 错误信息
     */
    error_message?: string | null;
};

/**
 * ScreeningStartRequest
 *
 * 简历筛选启动请求
 */
export type ScreeningStartRequest = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ScreeningTaskBrief
 *
 * 筛选任务简要信息
 */
export type ScreeningTaskBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Score
     */
    score: number | null;
    /**
     * Recommendation
     */
    recommendation: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ScreeningTaskCreate
 *
 * 创建筛选任务请求
 */
export type ScreeningTaskCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ScreeningTaskResponse
 *
 * 筛选任务响应
 */
export type ScreeningTaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Score
     */
    score: number | null;
    /**
     * Dimension Scores
     */
    dimension_scores: {
        [key: string]: unknown;
    } | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Recommendation
     */
    recommendation: string | null;
    /**
     * Report Content
     */
    report_content: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoAnalysisBrief
 *
 * 视频分析简要信息
 */
export type VideoAnalysisBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Video Name
     */
    video_name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Final Score
     */
    final_score?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * VideoAnalysisCreate
 *
 * 创建视频分析请求
 */
export type VideoAnalysisCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
    /**
     * Video Name
     *
     * 视频名称
     */
    video_name: string;
    /**
     * Video Path
     *
     * 视频存储路径
     */
    video_path?: string | null;
    /**
     * File Size
     *
     * 文件大小
     */
    file_size?: number;
    /**
     * Duration
     *
     * 视频时长(秒)
     */
    duration?: number;
};

/**
 * VideoAnalysisResponse
 *
 * 视频分析响应
 */
export type VideoAnalysisResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Video Name
     */
    video_name: string;
    /**
     * Video Path
     */
    video_path: string | null;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Duration
     */
    duration: number;
    /**
     * Status
     */
    status: string;
    /**
     * Error Message
     */
    error_message: string | null;
    big_five_scores?: BigFiveScores | null;
    /**
     * Confidence Score
     */
    confidence_score: number | null;
    /**
     * Fraud Score
     */
    fraud_score: number | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * VideoResultUpdate
 *
 * 更新视频分析结果请求
 */
export type VideoResultUpdate = {
    /**
     * Status
     *
     * 分析状态
     */
    status?: string | null;
    /**
     * Error Message
     *
     * 错误信息
     */
    error_message?: string | null;
    /**
     * Openness
     *
     * 开放性
     */
    openness?: number | null;
    /**
     * Conscientiousness
     *
     * 尽责性
     */
    conscientiousness?: number | null;
    /**
     * Extraversion
     *
     * 外向性
     */
    extraversion?: number | null;
    /**
     * Agreeableness
     *
     * 宜人性
     */
    agreeableness?: number | null;
    /**
     * Neuroticism
     *
     * 神经质
     */
    neuroticism?: number | null;
    /**
     * Confidence Score
     *
     * 置信度
     */
    confidence_score?: number | null;
    /**
     * Fraud Score
     *
     * 欺诈风险
     */
    fraud_score?: number | null;
    /**
     * Summary
     *
     * 分析摘要
     */
    summary?: string | null;
    /**
     * Raw Result
     *
     * 原始结果
     */
    raw_result?: {
        [key: string]: unknown;
    } | null;
};

export type GetPositionsApiV1PositionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Is Active
         *
         * 是否启用
         */
        is_active?: boolean | null;
    };
    url: '/api/v1/positions';
};

export type GetPositionsApiV1PositionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPositionsApiV1PositionsGetError = GetPositionsApiV1PositionsGetErrors[keyof GetPositionsApiV1PositionsGetErrors];

export type GetPositionsApiV1PositionsGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelPositionListResponse;
};

export type GetPositionsApiV1PositionsGetResponse = GetPositionsApiV1PositionsGetResponses[keyof GetPositionsApiV1PositionsGetResponses];

export type CreatePositionApiV1PositionsPostData = {
    body: PositionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/positions';
};

export type CreatePositionApiV1PositionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePositionApiV1PositionsPostError = CreatePositionApiV1PositionsPostErrors[keyof CreatePositionApiV1PositionsPostErrors];

export type CreatePositionApiV1PositionsPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPositionResponse;
};

export type CreatePositionApiV1PositionsPostResponse = CreatePositionApiV1PositionsPostResponses[keyof CreatePositionApiV1PositionsPostResponses];

export type DeletePositionApiV1PositionsPositionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type DeletePositionApiV1PositionsPositionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePositionApiV1PositionsPositionIdDeleteError = DeletePositionApiV1PositionsPositionIdDeleteErrors[keyof DeletePositionApiV1PositionsPositionIdDeleteErrors];

export type DeletePositionApiV1PositionsPositionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeletePositionApiV1PositionsPositionIdDeleteResponse = DeletePositionApiV1PositionsPositionIdDeleteResponses[keyof DeletePositionApiV1PositionsPositionIdDeleteResponses];

export type GetPositionApiV1PositionsPositionIdGetData = {
    body?: never;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type GetPositionApiV1PositionsPositionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPositionApiV1PositionsPositionIdGetError = GetPositionApiV1PositionsPositionIdGetErrors[keyof GetPositionApiV1PositionsPositionIdGetErrors];

export type GetPositionApiV1PositionsPositionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPositionResponse;
};

export type GetPositionApiV1PositionsPositionIdGetResponse = GetPositionApiV1PositionsPositionIdGetResponses[keyof GetPositionApiV1PositionsPositionIdGetResponses];

export type UpdatePositionApiV1PositionsPositionIdPatchData = {
    body: PositionUpdate;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type UpdatePositionApiV1PositionsPositionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePositionApiV1PositionsPositionIdPatchError = UpdatePositionApiV1PositionsPositionIdPatchErrors[keyof UpdatePositionApiV1PositionsPositionIdPatchErrors];

export type UpdatePositionApiV1PositionsPositionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPositionResponse;
};

export type UpdatePositionApiV1PositionsPositionIdPatchResponse = UpdatePositionApiV1PositionsPositionIdPatchResponses[keyof UpdatePositionApiV1PositionsPositionIdPatchResponses];

export type GetResumesApiV1ResumesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Keyword
         *
         * 搜索关键词(姓名)
         */
        keyword?: string | null;
    };
    url: '/api/v1/resumes';
};

export type GetResumesApiV1ResumesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResumesApiV1ResumesGetError = GetResumesApiV1ResumesGetErrors[keyof GetResumesApiV1ResumesGetErrors];

export type GetResumesApiV1ResumesGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelResumeListResponse;
};

export type GetResumesApiV1ResumesGetResponse = GetResumesApiV1ResumesGetResponses[keyof GetResumesApiV1ResumesGetResponses];

export type CreateResumeApiV1ResumesPostData = {
    body: ResumeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/resumes';
};

export type CreateResumeApiV1ResumesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResumeApiV1ResumesPostError = CreateResumeApiV1ResumesPostErrors[keyof CreateResumeApiV1ResumesPostErrors];

export type CreateResumeApiV1ResumesPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelResumeResponse;
};

export type CreateResumeApiV1ResumesPostResponse = CreateResumeApiV1ResumesPostResponses[keyof CreateResumeApiV1ResumesPostResponses];

export type CheckHashApiV1ResumesCheckHashGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File Hash
         *
         * 文件哈希值
         */
        file_hash: string;
    };
    url: '/api/v1/resumes/check-hash';
};

export type CheckHashApiV1ResumesCheckHashGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckHashApiV1ResumesCheckHashGetError = CheckHashApiV1ResumesCheckHashGetErrors[keyof CheckHashApiV1ResumesCheckHashGetErrors];

export type CheckHashApiV1ResumesCheckHashGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelHashCheckData;
};

export type CheckHashApiV1ResumesCheckHashGetResponse = CheckHashApiV1ResumesCheckHashGetResponses[keyof CheckHashApiV1ResumesCheckHashGetResponses];

export type DeleteResumeApiV1ResumesResumeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type DeleteResumeApiV1ResumesResumeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteResumeApiV1ResumesResumeIdDeleteError = DeleteResumeApiV1ResumesResumeIdDeleteErrors[keyof DeleteResumeApiV1ResumesResumeIdDeleteErrors];

export type DeleteResumeApiV1ResumesResumeIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteResumeApiV1ResumesResumeIdDeleteResponse = DeleteResumeApiV1ResumesResumeIdDeleteResponses[keyof DeleteResumeApiV1ResumesResumeIdDeleteResponses];

export type GetResumeApiV1ResumesResumeIdGetData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type GetResumeApiV1ResumesResumeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResumeApiV1ResumesResumeIdGetError = GetResumeApiV1ResumesResumeIdGetErrors[keyof GetResumeApiV1ResumesResumeIdGetErrors];

export type GetResumeApiV1ResumesResumeIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelResumeResponse;
};

export type GetResumeApiV1ResumesResumeIdGetResponse = GetResumeApiV1ResumesResumeIdGetResponses[keyof GetResumeApiV1ResumesResumeIdGetResponses];

export type UpdateResumeApiV1ResumesResumeIdPatchData = {
    body: ResumeUpdate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type UpdateResumeApiV1ResumesResumeIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateResumeApiV1ResumesResumeIdPatchError = UpdateResumeApiV1ResumesResumeIdPatchErrors[keyof UpdateResumeApiV1ResumesResumeIdPatchErrors];

export type UpdateResumeApiV1ResumesResumeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelResumeResponse;
};

export type UpdateResumeApiV1ResumesResumeIdPatchResponse = UpdateResumeApiV1ResumesResumeIdPatchResponses[keyof UpdateResumeApiV1ResumesResumeIdPatchResponses];

export type BatchDeleteResumesApiV1ResumesBatchDeletePostData = {
    body: BatchDeleteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/resumes/batch-delete';
};

export type BatchDeleteResumesApiV1ResumesBatchDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchDeleteResumesApiV1ResumesBatchDeletePostError = BatchDeleteResumesApiV1ResumesBatchDeletePostErrors[keyof BatchDeleteResumesApiV1ResumesBatchDeletePostErrors];

export type BatchDeleteResumesApiV1ResumesBatchDeletePostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelBatchDeleteData;
};

export type BatchDeleteResumesApiV1ResumesBatchDeletePostResponse = BatchDeleteResumesApiV1ResumesBatchDeletePostResponses[keyof BatchDeleteResumesApiV1ResumesBatchDeletePostResponses];

export type CheckHashesApiV1ResumesCheckHashesPostData = {
    body: CheckHashesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/resumes/check-hashes';
};

export type CheckHashesApiV1ResumesCheckHashesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckHashesApiV1ResumesCheckHashesPostError = CheckHashesApiV1ResumesCheckHashesPostErrors[keyof CheckHashesApiV1ResumesCheckHashesPostErrors];

export type CheckHashesApiV1ResumesCheckHashesPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelBatchHashCheckData;
};

export type CheckHashesApiV1ResumesCheckHashesPostResponse = CheckHashesApiV1ResumesCheckHashesPostResponses[keyof CheckHashesApiV1ResumesCheckHashesPostResponses];

export type GetApplicationsApiV1ApplicationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Position Id
         *
         * 岗位ID筛选
         */
        position_id?: string | null;
        /**
         * Resume Id
         *
         * 简历ID筛选
         */
        resume_id?: string | null;
    };
    url: '/api/v1/applications';
};

export type GetApplicationsApiV1ApplicationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApplicationsApiV1ApplicationsGetError = GetApplicationsApiV1ApplicationsGetErrors[keyof GetApplicationsApiV1ApplicationsGetErrors];

export type GetApplicationsApiV1ApplicationsGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelApplicationListResponse;
};

export type GetApplicationsApiV1ApplicationsGetResponse = GetApplicationsApiV1ApplicationsGetResponses[keyof GetApplicationsApiV1ApplicationsGetResponses];

export type CreateApplicationApiV1ApplicationsPostData = {
    body: ApplicationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/applications';
};

export type CreateApplicationApiV1ApplicationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApplicationApiV1ApplicationsPostError = CreateApplicationApiV1ApplicationsPostErrors[keyof CreateApplicationApiV1ApplicationsPostErrors];

export type CreateApplicationApiV1ApplicationsPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelApplicationResponse;
};

export type CreateApplicationApiV1ApplicationsPostResponse = CreateApplicationApiV1ApplicationsPostResponses[keyof CreateApplicationApiV1ApplicationsPostResponses];

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_id}';
};

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteError = DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors[keyof DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors];

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponse = DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses[keyof DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses];

export type GetApplicationApiV1ApplicationsApplicationIdGetData = {
    body?: never;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_id}';
};

export type GetApplicationApiV1ApplicationsApplicationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApplicationApiV1ApplicationsApplicationIdGetError = GetApplicationApiV1ApplicationsApplicationIdGetErrors[keyof GetApplicationApiV1ApplicationsApplicationIdGetErrors];

export type GetApplicationApiV1ApplicationsApplicationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelApplicationDetailResponse;
};

export type GetApplicationApiV1ApplicationsApplicationIdGetResponse = GetApplicationApiV1ApplicationsApplicationIdGetResponses[keyof GetApplicationApiV1ApplicationsApplicationIdGetResponses];

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchData = {
    body: ApplicationUpdate;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_id}';
};

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchError = UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors[keyof UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors];

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelApplicationResponse;
};

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchResponse = UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses[keyof UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses];

export type GetStatsOverviewApiV1ApplicationsStatsOverviewGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/applications/stats/overview';
};

export type GetStatsOverviewApiV1ApplicationsStatsOverviewGetResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetStatsOverviewApiV1ApplicationsStatsOverviewGetResponse = GetStatsOverviewApiV1ApplicationsStatsOverviewGetResponses[keyof GetStatsOverviewApiV1ApplicationsStatsOverviewGetResponses];

export type GetScreeningTasksApiV1ScreeningGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
        /**
         * Status
         *
         * 状态筛选
         */
        status?: string | null;
    };
    url: '/api/v1/screening';
};

export type GetScreeningTasksApiV1ScreeningGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreeningTasksApiV1ScreeningGetError = GetScreeningTasksApiV1ScreeningGetErrors[keyof GetScreeningTasksApiV1ScreeningGetErrors];

export type GetScreeningTasksApiV1ScreeningGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelScreeningTaskResponse;
};

export type GetScreeningTasksApiV1ScreeningGetResponse = GetScreeningTasksApiV1ScreeningGetResponses[keyof GetScreeningTasksApiV1ScreeningGetResponses];

export type CreateScreeningTaskApiV1ScreeningPostData = {
    body: ScreeningTaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/screening';
};

export type CreateScreeningTaskApiV1ScreeningPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScreeningTaskApiV1ScreeningPostError = CreateScreeningTaskApiV1ScreeningPostErrors[keyof CreateScreeningTaskApiV1ScreeningPostErrors];

export type CreateScreeningTaskApiV1ScreeningPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelScreeningTaskResponse;
};

export type CreateScreeningTaskApiV1ScreeningPostResponse = CreateScreeningTaskApiV1ScreeningPostResponses[keyof CreateScreeningTaskApiV1ScreeningPostResponses];

export type DeleteScreeningTaskApiV1ScreeningTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}';
};

export type DeleteScreeningTaskApiV1ScreeningTaskIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScreeningTaskApiV1ScreeningTaskIdDeleteError = DeleteScreeningTaskApiV1ScreeningTaskIdDeleteErrors[keyof DeleteScreeningTaskApiV1ScreeningTaskIdDeleteErrors];

export type DeleteScreeningTaskApiV1ScreeningTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteScreeningTaskApiV1ScreeningTaskIdDeleteResponse = DeleteScreeningTaskApiV1ScreeningTaskIdDeleteResponses[keyof DeleteScreeningTaskApiV1ScreeningTaskIdDeleteResponses];

export type GetScreeningTaskApiV1ScreeningTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}';
};

export type GetScreeningTaskApiV1ScreeningTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreeningTaskApiV1ScreeningTaskIdGetError = GetScreeningTaskApiV1ScreeningTaskIdGetErrors[keyof GetScreeningTaskApiV1ScreeningTaskIdGetErrors];

export type GetScreeningTaskApiV1ScreeningTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelScreeningTaskResponse;
};

export type GetScreeningTaskApiV1ScreeningTaskIdGetResponse = GetScreeningTaskApiV1ScreeningTaskIdGetResponses[keyof GetScreeningTaskApiV1ScreeningTaskIdGetResponses];

export type UpdateScreeningResultApiV1ScreeningTaskIdPatchData = {
    body: ScreeningResultUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}';
};

export type UpdateScreeningResultApiV1ScreeningTaskIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScreeningResultApiV1ScreeningTaskIdPatchError = UpdateScreeningResultApiV1ScreeningTaskIdPatchErrors[keyof UpdateScreeningResultApiV1ScreeningTaskIdPatchErrors];

export type UpdateScreeningResultApiV1ScreeningTaskIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelScreeningTaskResponse;
};

export type UpdateScreeningResultApiV1ScreeningTaskIdPatchResponse = UpdateScreeningResultApiV1ScreeningTaskIdPatchResponses[keyof UpdateScreeningResultApiV1ScreeningTaskIdPatchResponses];

export type GetScreeningStatusApiV1ScreeningTaskIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}/status';
};

export type GetScreeningStatusApiV1ScreeningTaskIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreeningStatusApiV1ScreeningTaskIdStatusGetError = GetScreeningStatusApiV1ScreeningTaskIdStatusGetErrors[keyof GetScreeningStatusApiV1ScreeningTaskIdStatusGetErrors];

export type GetScreeningStatusApiV1ScreeningTaskIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetScreeningStatusApiV1ScreeningTaskIdStatusGetResponse = GetScreeningStatusApiV1ScreeningTaskIdStatusGetResponses[keyof GetScreeningStatusApiV1ScreeningTaskIdStatusGetResponses];

export type DownloadScreeningReportApiV1ScreeningTaskIdDownloadGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}/download';
};

export type DownloadScreeningReportApiV1ScreeningTaskIdDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadScreeningReportApiV1ScreeningTaskIdDownloadGetError = DownloadScreeningReportApiV1ScreeningTaskIdDownloadGetErrors[keyof DownloadScreeningReportApiV1ScreeningTaskIdDownloadGetErrors];

export type DownloadScreeningReportApiV1ScreeningTaskIdDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVideoAnalysesApiV1VideoGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
        /**
         * Status
         *
         * 状态筛选
         */
        status?: string | null;
    };
    url: '/api/v1/video';
};

export type GetVideoAnalysesApiV1VideoGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoAnalysesApiV1VideoGetError = GetVideoAnalysesApiV1VideoGetErrors[keyof GetVideoAnalysesApiV1VideoGetErrors];

export type GetVideoAnalysesApiV1VideoGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelVideoAnalysisResponse;
};

export type GetVideoAnalysesApiV1VideoGetResponse = GetVideoAnalysesApiV1VideoGetResponses[keyof GetVideoAnalysesApiV1VideoGetResponses];

export type CreateVideoAnalysisApiV1VideoPostData = {
    body: VideoAnalysisCreate;
    path?: never;
    query?: never;
    url: '/api/v1/video';
};

export type CreateVideoAnalysisApiV1VideoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVideoAnalysisApiV1VideoPostError = CreateVideoAnalysisApiV1VideoPostErrors[keyof CreateVideoAnalysisApiV1VideoPostErrors];

export type CreateVideoAnalysisApiV1VideoPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelVideoAnalysisResponse;
};

export type CreateVideoAnalysisApiV1VideoPostResponse = CreateVideoAnalysisApiV1VideoPostResponses[keyof CreateVideoAnalysisApiV1VideoPostResponses];

export type DeleteVideoAnalysisApiV1VideoVideoIdDeleteData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}';
};

export type DeleteVideoAnalysisApiV1VideoVideoIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVideoAnalysisApiV1VideoVideoIdDeleteError = DeleteVideoAnalysisApiV1VideoVideoIdDeleteErrors[keyof DeleteVideoAnalysisApiV1VideoVideoIdDeleteErrors];

export type DeleteVideoAnalysisApiV1VideoVideoIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteVideoAnalysisApiV1VideoVideoIdDeleteResponse = DeleteVideoAnalysisApiV1VideoVideoIdDeleteResponses[keyof DeleteVideoAnalysisApiV1VideoVideoIdDeleteResponses];

export type GetVideoAnalysisApiV1VideoVideoIdGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}';
};

export type GetVideoAnalysisApiV1VideoVideoIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoAnalysisApiV1VideoVideoIdGetError = GetVideoAnalysisApiV1VideoVideoIdGetErrors[keyof GetVideoAnalysisApiV1VideoVideoIdGetErrors];

export type GetVideoAnalysisApiV1VideoVideoIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelVideoAnalysisResponse;
};

export type GetVideoAnalysisApiV1VideoVideoIdGetResponse = GetVideoAnalysisApiV1VideoVideoIdGetResponses[keyof GetVideoAnalysisApiV1VideoVideoIdGetResponses];

export type UpdateVideoResultApiV1VideoVideoIdPatchData = {
    body: VideoResultUpdate;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}';
};

export type UpdateVideoResultApiV1VideoVideoIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVideoResultApiV1VideoVideoIdPatchError = UpdateVideoResultApiV1VideoVideoIdPatchErrors[keyof UpdateVideoResultApiV1VideoVideoIdPatchErrors];

export type UpdateVideoResultApiV1VideoVideoIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelVideoAnalysisResponse;
};

export type UpdateVideoResultApiV1VideoVideoIdPatchResponse = UpdateVideoResultApiV1VideoVideoIdPatchResponses[keyof UpdateVideoResultApiV1VideoVideoIdPatchResponses];

export type GetVideoStatusApiV1VideoVideoIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}/status';
};

export type GetVideoStatusApiV1VideoVideoIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoStatusApiV1VideoVideoIdStatusGetError = GetVideoStatusApiV1VideoVideoIdStatusGetErrors[keyof GetVideoStatusApiV1VideoVideoIdStatusGetErrors];

export type GetVideoStatusApiV1VideoVideoIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetVideoStatusApiV1VideoVideoIdStatusGetResponse = GetVideoStatusApiV1VideoVideoIdStatusGetResponses[keyof GetVideoStatusApiV1VideoVideoIdStatusGetResponses];

export type GetInterviewSessionsApiV1InterviewGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
    };
    url: '/api/v1/interview';
};

export type GetInterviewSessionsApiV1InterviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewSessionsApiV1InterviewGetError = GetInterviewSessionsApiV1InterviewGetErrors[keyof GetInterviewSessionsApiV1InterviewGetErrors];

export type GetInterviewSessionsApiV1InterviewGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelInterviewSessionResponse;
};

export type GetInterviewSessionsApiV1InterviewGetResponse = GetInterviewSessionsApiV1InterviewGetResponses[keyof GetInterviewSessionsApiV1InterviewGetResponses];

export type CreateInterviewSessionApiV1InterviewPostData = {
    body: InterviewSessionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/interview';
};

export type CreateInterviewSessionApiV1InterviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInterviewSessionApiV1InterviewPostError = CreateInterviewSessionApiV1InterviewPostErrors[keyof CreateInterviewSessionApiV1InterviewPostErrors];

export type CreateInterviewSessionApiV1InterviewPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type CreateInterviewSessionApiV1InterviewPostResponse = CreateInterviewSessionApiV1InterviewPostResponses[keyof CreateInterviewSessionApiV1InterviewPostResponses];

export type DeleteInterviewSessionApiV1InterviewSessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}';
};

export type DeleteInterviewSessionApiV1InterviewSessionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteInterviewSessionApiV1InterviewSessionIdDeleteError = DeleteInterviewSessionApiV1InterviewSessionIdDeleteErrors[keyof DeleteInterviewSessionApiV1InterviewSessionIdDeleteErrors];

export type DeleteInterviewSessionApiV1InterviewSessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteInterviewSessionApiV1InterviewSessionIdDeleteResponse = DeleteInterviewSessionApiV1InterviewSessionIdDeleteResponses[keyof DeleteInterviewSessionApiV1InterviewSessionIdDeleteResponses];

export type GetInterviewSessionApiV1InterviewSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}';
};

export type GetInterviewSessionApiV1InterviewSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewSessionApiV1InterviewSessionIdGetError = GetInterviewSessionApiV1InterviewSessionIdGetErrors[keyof GetInterviewSessionApiV1InterviewSessionIdGetErrors];

export type GetInterviewSessionApiV1InterviewSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type GetInterviewSessionApiV1InterviewSessionIdGetResponse = GetInterviewSessionApiV1InterviewSessionIdGetResponses[keyof GetInterviewSessionApiV1InterviewSessionIdGetResponses];

export type GenerateQuestionsApiV1InterviewSessionIdQuestionsPostData = {
    body: GenerateQuestionsRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}/questions';
};

export type GenerateQuestionsApiV1InterviewSessionIdQuestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateQuestionsApiV1InterviewSessionIdQuestionsPostError = GenerateQuestionsApiV1InterviewSessionIdQuestionsPostErrors[keyof GenerateQuestionsApiV1InterviewSessionIdQuestionsPostErrors];

export type GenerateQuestionsApiV1InterviewSessionIdQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GenerateQuestionsApiV1InterviewSessionIdQuestionsPostResponse = GenerateQuestionsApiV1InterviewSessionIdQuestionsPostResponses[keyof GenerateQuestionsApiV1InterviewSessionIdQuestionsPostResponses];

export type RecordQaApiV1InterviewSessionIdQaPostData = {
    body: QaRecordCreate;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}/qa';
};

export type RecordQaApiV1InterviewSessionIdQaPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecordQaApiV1InterviewSessionIdQaPostError = RecordQaApiV1InterviewSessionIdQaPostErrors[keyof RecordQaApiV1InterviewSessionIdQaPostErrors];

export type RecordQaApiV1InterviewSessionIdQaPostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type RecordQaApiV1InterviewSessionIdQaPostResponse = RecordQaApiV1InterviewSessionIdQaPostResponses[keyof RecordQaApiV1InterviewSessionIdQaPostResponses];

export type CompleteSessionApiV1InterviewSessionIdCompletePostData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}/complete';
};

export type CompleteSessionApiV1InterviewSessionIdCompletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteSessionApiV1InterviewSessionIdCompletePostError = CompleteSessionApiV1InterviewSessionIdCompletePostErrors[keyof CompleteSessionApiV1InterviewSessionIdCompletePostErrors];

export type CompleteSessionApiV1InterviewSessionIdCompletePostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type CompleteSessionApiV1InterviewSessionIdCompletePostResponse = CompleteSessionApiV1InterviewSessionIdCompletePostResponses[keyof CompleteSessionApiV1InterviewSessionIdCompletePostResponses];

export type GetAnalysesApiV1AnalysisGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
        /**
         * Recommendation Level
         *
         * 推荐等级筛选
         */
        recommendation_level?: string | null;
    };
    url: '/api/v1/analysis';
};

export type GetAnalysesApiV1AnalysisGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysesApiV1AnalysisGetError = GetAnalysesApiV1AnalysisGetErrors[keyof GetAnalysesApiV1AnalysisGetErrors];

export type GetAnalysesApiV1AnalysisGetResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelComprehensiveAnalysisResponse;
};

export type GetAnalysesApiV1AnalysisGetResponse = GetAnalysesApiV1AnalysisGetResponses[keyof GetAnalysesApiV1AnalysisGetResponses];

export type CreateAnalysisApiV1AnalysisPostData = {
    body: ComprehensiveAnalysisCreate;
    path?: never;
    query?: never;
    url: '/api/v1/analysis';
};

export type CreateAnalysisApiV1AnalysisPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisApiV1AnalysisPostError = CreateAnalysisApiV1AnalysisPostErrors[keyof CreateAnalysisApiV1AnalysisPostErrors];

export type CreateAnalysisApiV1AnalysisPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelComprehensiveAnalysisResponse;
};

export type CreateAnalysisApiV1AnalysisPostResponse = CreateAnalysisApiV1AnalysisPostResponses[keyof CreateAnalysisApiV1AnalysisPostResponses];

export type DeleteAnalysisApiV1AnalysisAnalysisIdDeleteData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analysis/{analysis_id}';
};

export type DeleteAnalysisApiV1AnalysisAnalysisIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisApiV1AnalysisAnalysisIdDeleteError = DeleteAnalysisApiV1AnalysisAnalysisIdDeleteErrors[keyof DeleteAnalysisApiV1AnalysisAnalysisIdDeleteErrors];

export type DeleteAnalysisApiV1AnalysisAnalysisIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteAnalysisApiV1AnalysisAnalysisIdDeleteResponse = DeleteAnalysisApiV1AnalysisAnalysisIdDeleteResponses[keyof DeleteAnalysisApiV1AnalysisAnalysisIdDeleteResponses];

export type GetAnalysisApiV1AnalysisAnalysisIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analysis/{analysis_id}';
};

export type GetAnalysisApiV1AnalysisAnalysisIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisApiV1AnalysisAnalysisIdGetError = GetAnalysisApiV1AnalysisAnalysisIdGetErrors[keyof GetAnalysisApiV1AnalysisAnalysisIdGetErrors];

export type GetAnalysisApiV1AnalysisAnalysisIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelComprehensiveAnalysisResponse;
};

export type GetAnalysisApiV1AnalysisAnalysisIdGetResponse = GetAnalysisApiV1AnalysisAnalysisIdGetResponses[keyof GetAnalysisApiV1AnalysisAnalysisIdGetResponses];

export type GetRecommendationStatsApiV1AnalysisStatsRecommendationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/analysis/stats/recommendation';
};

export type GetRecommendationStatsApiV1AnalysisStatsRecommendationGetResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetRecommendationStatsApiV1AnalysisStatsRecommendationGetResponse = GetRecommendationStatsApiV1AnalysisStatsRecommendationGetResponses[keyof GetRecommendationStatsApiV1AnalysisStatsRecommendationGetResponses];

export type GetAiStatusApiV1AiStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/status';
};

export type GetAiStatusApiV1AiStatusGetResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetAiStatusApiV1AiStatusGetResponse = GetAiStatusApiV1AiStatusGetResponses[keyof GetAiStatusApiV1AiStatusGetResponses];

export type AiGeneratePositionApiV1AiPositionGeneratePostData = {
    body: PositionGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/position/generate';
};

export type AiGeneratePositionApiV1AiPositionGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGeneratePositionApiV1AiPositionGeneratePostError = AiGeneratePositionApiV1AiPositionGeneratePostErrors[keyof AiGeneratePositionApiV1AiPositionGeneratePostErrors];

export type AiGeneratePositionApiV1AiPositionGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGeneratePositionApiV1AiPositionGeneratePostResponse = AiGeneratePositionApiV1AiPositionGeneratePostResponses[keyof AiGeneratePositionApiV1AiPositionGeneratePostResponses];

export type StartAiScreeningApiV1AiScreeningStartPostData = {
    body: ScreeningStartRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/screening/start';
};

export type StartAiScreeningApiV1AiScreeningStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartAiScreeningApiV1AiScreeningStartPostError = StartAiScreeningApiV1AiScreeningStartPostErrors[keyof StartAiScreeningApiV1AiScreeningStartPostErrors];

export type StartAiScreeningApiV1AiScreeningStartPostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type StartAiScreeningApiV1AiScreeningStartPostResponse = StartAiScreeningApiV1AiScreeningStartPostResponses[keyof StartAiScreeningApiV1AiScreeningStartPostResponses];

export type AiGenerateQuestionsApiV1AiInterviewQuestionsPostData = {
    body: InterviewQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/questions';
};

export type AiGenerateQuestionsApiV1AiInterviewQuestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGenerateQuestionsApiV1AiInterviewQuestionsPostError = AiGenerateQuestionsApiV1AiInterviewQuestionsPostErrors[keyof AiGenerateQuestionsApiV1AiInterviewQuestionsPostErrors];

export type AiGenerateQuestionsApiV1AiInterviewQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGenerateQuestionsApiV1AiInterviewQuestionsPostResponse = AiGenerateQuestionsApiV1AiInterviewQuestionsPostResponses[keyof AiGenerateQuestionsApiV1AiInterviewQuestionsPostResponses];

export type AiEvaluateAnswerApiV1AiInterviewEvaluatePostData = {
    body: AnswerEvaluateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/evaluate';
};

export type AiEvaluateAnswerApiV1AiInterviewEvaluatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiEvaluateAnswerApiV1AiInterviewEvaluatePostError = AiEvaluateAnswerApiV1AiInterviewEvaluatePostErrors[keyof AiEvaluateAnswerApiV1AiInterviewEvaluatePostErrors];

export type AiEvaluateAnswerApiV1AiInterviewEvaluatePostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiEvaluateAnswerApiV1AiInterviewEvaluatePostResponse = AiEvaluateAnswerApiV1AiInterviewEvaluatePostResponses[keyof AiEvaluateAnswerApiV1AiInterviewEvaluatePostResponses];

export type AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostData = {
    body: CandidateQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/candidate-questions';
};

export type AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostError = AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostErrors[keyof AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostErrors];

export type AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostResponse = AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostResponses[keyof AiGenerateCandidateQuestionsApiV1AiInterviewCandidateQuestionsPostResponses];

export type AiGenerateReportApiV1AiInterviewReportPostData = {
    body: FinalReportRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/report';
};

export type AiGenerateReportApiV1AiInterviewReportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGenerateReportApiV1AiInterviewReportPostError = AiGenerateReportApiV1AiInterviewReportPostErrors[keyof AiGenerateReportApiV1AiInterviewReportPostErrors];

export type AiGenerateReportApiV1AiInterviewReportPostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGenerateReportApiV1AiInterviewReportPostResponse = AiGenerateReportApiV1AiInterviewReportPostResponses[keyof AiGenerateReportApiV1AiInterviewReportPostResponses];

export type AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostData = {
    body: ComprehensiveAnalysisRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/analysis/comprehensive';
};

export type AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostError = AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostErrors[keyof AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostErrors];

export type AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostResponse = AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostResponses[keyof AiComprehensiveAnalysisApiV1AiAnalysisComprehensivePostResponses];

export type GenerateRandomResumeApiV1AiDevRandomResumePostData = {
    body: RandomResumeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/dev/random-resume';
};

export type GenerateRandomResumeApiV1AiDevRandomResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateRandomResumeApiV1AiDevRandomResumePostError = GenerateRandomResumeApiV1AiDevRandomResumePostErrors[keyof GenerateRandomResumeApiV1AiDevRandomResumePostErrors];

export type GenerateRandomResumeApiV1AiDevRandomResumePostResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GenerateRandomResumeApiV1AiDevRandomResumePostResponse = GenerateRandomResumeApiV1AiDevRandomResumePostResponses[keyof GenerateRandomResumeApiV1AiDevRandomResumePostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
