// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ApplicationCreate
 *
 * 创建应聘申请请求
 */
export type ApplicationCreate = {
    /**
     * Position Id
     *
     * 岗位ID
     */
    position_id: string;
    /**
     * Resume Id
     *
     * 简历ID
     */
    resume_id: string;
    /**
     * Notes
     *
     * 备注
     */
    notes?: string | null;
};

/**
 * ApplicationDetailResponse
 *
 * 应聘申请详情响应（包含关联数据）
 */
export type ApplicationDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Position Id
     */
    position_id: string;
    /**
     * Resume Id
     */
    resume_id: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    position?: PositionListResponse | null;
    resume?: ResumeListResponse | null;
    screening_task?: ScreeningTaskBrief | null;
    video_analysis?: VideoAnalysisBrief | null;
    interview_session?: InterviewSessionBrief | null;
    comprehensive_analysis?: ComprehensiveAnalysisBrief | null;
};

/**
 * ApplicationResponse
 *
 * 应聘申请响应
 */
export type ApplicationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Position Id
     */
    position_id: string;
    /**
     * Resume Id
     */
    resume_id: string;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
};

/**
 * ApplicationUpdate
 *
 * 更新应聘申请请求
 */
export type ApplicationUpdate = {
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * BatchDeleteData
 *
 * 批量删除结果
 */
export type BatchDeleteData = {
    /**
     * Deleted Count
     */
    deleted_count: number;
    /**
     * Requested Count
     */
    requested_count: number;
};

/**
 * BatchDeleteRequest
 *
 * 批量删除请求
 */
export type BatchDeleteRequest = {
    /**
     * Resume Ids
     *
     * 简历ID列表
     */
    resume_ids: Array<string>;
};

/**
 * BatchHashCheckData
 *
 * 批量哈希检查结果
 */
export type BatchHashCheckData = {
    /**
     * Exists
     */
    exists: {
        [key: string]: boolean;
    };
    /**
     * Existing Count
     */
    existing_count: number;
};

/**
 * BigFiveScores
 *
 * 大五人格评分
 */
export type BigFiveScores = {
    /**
     * Openness
     *
     * 开放性
     */
    openness?: number | null;
    /**
     * Conscientiousness
     *
     * 尽责性
     */
    conscientiousness?: number | null;
    /**
     * Extraversion
     *
     * 外向性
     */
    extraversion?: number | null;
    /**
     * Agreeableness
     *
     * 宜人性
     */
    agreeableness?: number | null;
    /**
     * Neuroticism
     *
     * 神经质
     */
    neuroticism?: number | null;
};

/**
 * CandidateQuestionsRequest
 */
export type CandidateQuestionsRequest = {
    /**
     * Session Id
     *
     * 面试会话ID，用于查询上下文
     */
    session_id?: string | null;
    /**
     * Current Question
     *
     * 当前问题
     */
    current_question: string;
    /**
     * Current Answer
     *
     * 当前回答
     */
    current_answer: string;
    /**
     * Conversation History
     *
     * 历史对话
     */
    conversation_history?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Resume Summary
     *
     * 简历摘要
     */
    resume_summary?: string | null;
    /**
     * Followup Count
     *
     * 追问数量
     */
    followup_count?: number;
    /**
     * Alternative Count
     *
     * 候选问题数量
     */
    alternative_count?: number;
};

/**
 * CheckHashesRequest
 *
 * 批量哈希检查请求
 */
export type CheckHashesRequest = {
    /**
     * Hashes
     *
     * 哈希值列表
     */
    hashes: Array<string>;
};

/**
 * ComprehensiveAnalysisBrief
 *
 * 综合分析简要信息
 */
export type ComprehensiveAnalysisBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Final Score
     */
    final_score: number;
    /**
     * Recommendation Level
     */
    recommendation_level: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ComprehensiveAnalysisCreate
 *
 * 创建综合分析请求
 */
export type ComprehensiveAnalysisCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ComprehensiveAnalysisRequest
 *
 * 综合分析请求
 */
export type ComprehensiveAnalysisRequest = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ComprehensiveAnalysisResponse
 *
 * 综合分析响应
 */
export type ComprehensiveAnalysisResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Final Score
     */
    final_score: number;
    /**
     * Recommendation Level
     */
    recommendation_level: string;
    /**
     * Recommendation Reason
     */
    recommendation_reason: string | null;
    /**
     * Suggested Action
     */
    suggested_action: string | null;
    /**
     * Dimension Scores
     */
    dimension_scores?: {
        [key: string]: DimensionScoreItem;
    };
    /**
     * Report
     */
    report: string | null;
    /**
     * Input Snapshot
     */
    input_snapshot: {
        [key: string]: unknown;
    };
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * ComprehensiveAnalysisUpdate
 *
 * 更新综合分析请求
 */
export type ComprehensiveAnalysisUpdate = {
    /**
     * Final Score
     *
     * 综合得分
     */
    final_score?: number | null;
    /**
     * Recommendation Level
     *
     * 推荐等级
     */
    recommendation_level?: string | null;
    /**
     * Recommendation Reason
     *
     * 推荐理由
     */
    recommendation_reason?: string | null;
    /**
     * Suggested Action
     *
     * 建议行动
     */
    suggested_action?: string | null;
    /**
     * Dimension Scores
     *
     * 各维度评分
     */
    dimension_scores?: {
        [key: string]: unknown;
    } | null;
    /**
     * Report
     *
     * 分析报告
     */
    report?: string | null;
    /**
     * Input Snapshot
     *
     * 输入数据快照
     */
    input_snapshot?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DictResponse
 *
 * 字典数据响应
 */
export type DictResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DimensionScoreItem
 *
 * 单个维度评分项
 */
export type DimensionScoreItem = {
    /**
     * Dimension Score
     *
     * 维度评分(1-5)
     */
    dimension_score?: number | null;
    /**
     * Dimension Name
     *
     * 维度名称
     */
    dimension_name?: string | null;
    /**
     * Weight
     *
     * 权重
     */
    weight?: number | null;
    /**
     * Sub Scores
     *
     * 子维度评分
     */
    sub_scores?: {
        [key: string]: number;
    } | null;
    /**
     * Strengths
     *
     * 优势列表
     */
    strengths?: Array<string> | null;
    /**
     * Weaknesses
     *
     * 不足列表
     */
    weaknesses?: Array<string> | null;
    /**
     * Analysis
     *
     * 详细分析说明
     */
    analysis?: string | null;
};

/**
 * FeedbackRequest
 *
 * HR 反馈请求
 */
export type FeedbackRequest = {
    /**
     * Category
     *
     * 报告类别: screening/interview/analysis
     */
    category: string;
    /**
     * Target Id
     *
     * 目标 ID (task_id/session_id/analysis_id)
     */
    target_id: string;
    /**
     * Feedback
     *
     * HR 反馈内容
     */
    feedback: string;
};

/**
 * FeedbackResponse
 *
 * 反馈处理响应
 */
export type FeedbackResponse = {
    /**
     * Learned Rule
     *
     * 提炼的经验规则
     */
    learned_rule: string;
    /**
     * New Report
     *
     * 重新生成的报告内容
     */
    new_report?: string | null;
    /**
     * Experience Id
     *
     * 存储的经验 ID
     */
    experience_id: string;
};

/**
 * FinalReportRequest
 *
 * 最终报告生成请求
 */
export type FinalReportRequest = {
    /**
     * Session Id
     *
     * 面试会话ID
     */
    session_id: string;
    /**
     * Hr Notes
     *
     * HR备注
     */
    hr_notes?: string | null;
};

/**
 * GenerateQuestionsRequest
 *
 * 生成问题请求
 */
export type GenerateQuestionsRequest = {
    /**
     * Count
     *
     * 生成问题数量
     */
    count?: number;
    /**
     * Difficulty
     *
     * 难度: easy/medium/hard
     */
    difficulty?: string;
    /**
     * Focus Areas
     *
     * 关注领域
     */
    focus_areas?: Array<string> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HashCheckData
 *
 * 哈希检查结果
 */
export type HashCheckData = {
    /**
     * Exists
     */
    exists: boolean;
};

/**
 * InterviewQuestionsRequest
 *
 * 面试问题生成请求
 */
export type InterviewQuestionsRequest = {
    /**
     * Session Id
     *
     * 面试会话ID
     */
    session_id: string;
    /**
     * Resume Content
     *
     * 简历内容
     */
    resume_content?: string | null;
    /**
     * Count
     *
     * 问题数量
     */
    count?: number;
    /**
     * Interest Point Count
     *
     * 兴趣点数量
     */
    interest_point_count?: number;
};

/**
 * InterviewSessionBrief
 *
 * 面试会话简要信息
 */
export type InterviewSessionBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Interview Type
     */
    interview_type: string;
    /**
     * Is Completed
     */
    is_completed: boolean;
    /**
     * Final Score
     */
    final_score: number | null;
    /**
     * Message Count
     */
    message_count?: number;
    /**
     * Has Report
     */
    has_report?: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * InterviewSessionCreate
 *
 * 创建面试会话请求
 */
export type InterviewSessionCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
    /**
     * Interview Type
     *
     * 面试类型
     */
    interview_type?: string;
    /**
     * Config
     *
     * 面试配置
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * InterviewSessionResponse
 *
 * 面试会话响应
 */
export type InterviewSessionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Interview Type
     */
    interview_type: string;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Messages
     */
    messages: Array<QaMessage>;
    /**
     * Question Pool
     */
    question_pool: Array<string>;
    /**
     * Is Completed
     */
    is_completed: boolean;
    /**
     * Final Score
     */
    final_score: number | null;
    /**
     * Report
     */
    report: {
        [key: string]: unknown;
    } | null;
    /**
     * Report Markdown
     */
    report_markdown: string | null;
    /**
     * Message Count
     */
    message_count?: number;
    /**
     * Has Report
     */
    has_report?: boolean;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * InterviewSessionUpdate
 *
 * 更新面试会话请求
 */
export type InterviewSessionUpdate = {
    /**
     * Interview Type
     */
    interview_type?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Question Pool
     */
    question_pool?: Array<string> | null;
    /**
     * Is Completed
     */
    is_completed?: boolean | null;
    /**
     * Final Score
     */
    final_score?: number | null;
    /**
     * Report
     */
    report?: {
        [key: string]: unknown;
    } | null;
    /**
     * Report Markdown
     */
    report_markdown?: string | null;
};

/**
 * MessageResponse
 *
 * 仅消息响应（无数据）
 */
export type MessageResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    /**
     * Data
     */
    data?: null;
};

/**
 * MessagesSyncRequest
 *
 * 同步消息请求
 */
export type MessagesSyncRequest = {
    /**
     * Messages
     *
     * 完整对话记录
     */
    messages: Array<QaMessageCreate>;
};

/**
 * PagedData[ApplicationDetailResponse]
 */
export type PagedDataApplicationDetailResponseInput = {
    /**
     * Items
     */
    items: Array<ApplicationDetailResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ApplicationDetailResponse]
 */
export type PagedDataApplicationDetailResponseOutput = {
    /**
     * Items
     */
    items: Array<ApplicationDetailResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ComprehensiveAnalysisResponse]
 */
export type PagedDataComprehensiveAnalysisResponseInput = {
    /**
     * Items
     */
    items: Array<ComprehensiveAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ComprehensiveAnalysisResponse]
 */
export type PagedDataComprehensiveAnalysisResponseOutput = {
    /**
     * Items
     */
    items: Array<ComprehensiveAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[InterviewSessionResponse]
 */
export type PagedDataInterviewSessionResponseInput = {
    /**
     * Items
     */
    items: Array<InterviewSessionResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[InterviewSessionResponse]
 */
export type PagedDataInterviewSessionResponseOutput = {
    /**
     * Items
     */
    items: Array<InterviewSessionResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[PositionListResponse]
 */
export type PagedDataPositionListResponse = {
    /**
     * Items
     */
    items: Array<PositionListResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ResumeListResponse]
 */
export type PagedDataResumeListResponse = {
    /**
     * Items
     */
    items: Array<ResumeListResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ScreeningTaskResponse]
 */
export type PagedDataScreeningTaskResponseInput = {
    /**
     * Items
     */
    items: Array<ScreeningTaskResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[ScreeningTaskResponse]
 */
export type PagedDataScreeningTaskResponseOutput = {
    /**
     * Items
     */
    items: Array<ScreeningTaskResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[VideoAnalysisResponse]
 */
export type PagedDataVideoAnalysisResponseInput = {
    /**
     * Items
     */
    items: Array<VideoAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedData[VideoAnalysisResponse]
 */
export type PagedDataVideoAnalysisResponseOutput = {
    /**
     * Items
     */
    items: Array<VideoAnalysisResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Pages
     */
    pages: number;
};

/**
 * PagedResponseModel[ApplicationDetailResponse]
 */
export type PagedResponseModelApplicationDetailResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataApplicationDetailResponseOutput;
};

/**
 * PagedResponseModel[ComprehensiveAnalysisResponse]
 */
export type PagedResponseModelComprehensiveAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataComprehensiveAnalysisResponseOutput;
};

/**
 * PagedResponseModel[InterviewSessionResponse]
 */
export type PagedResponseModelInterviewSessionResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataInterviewSessionResponseOutput;
};

/**
 * PagedResponseModel[PositionListResponse]
 */
export type PagedResponseModelPositionListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataPositionListResponse;
};

/**
 * PagedResponseModel[ResumeListResponse]
 */
export type PagedResponseModelResumeListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataResumeListResponse;
};

/**
 * PagedResponseModel[ScreeningTaskResponse]
 */
export type PagedResponseModelScreeningTaskResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataScreeningTaskResponseOutput;
};

/**
 * PagedResponseModel[VideoAnalysisResponse]
 */
export type PagedResponseModelVideoAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data: PagedDataVideoAnalysisResponseOutput;
};

/**
 * PositionCreate
 *
 * 创建岗位请求
 */
export type PositionCreate = {
    /**
     * Title
     *
     * 岗位名称
     */
    title: string;
    /**
     * Department
     *
     * 所属部门
     */
    department?: string | null;
    /**
     * Description
     *
     * 岗位描述/JD
     */
    description?: string | null;
    /**
     * Required Skills
     *
     * 必备技能
     */
    required_skills?: Array<string>;
    /**
     * Optional Skills
     *
     * 可选技能
     */
    optional_skills?: Array<string>;
    /**
     * Min Experience
     *
     * 最低工作年限
     */
    min_experience?: number;
    /**
     * Education
     *
     * 学历要求
     */
    education?: Array<string>;
    /**
     * Salary Min
     *
     * 最低薪资(K)
     */
    salary_min?: number;
    /**
     * Salary Max
     *
     * 最高薪资(K)
     */
    salary_max?: number;
};

/**
 * PositionGenerateRequest
 *
 * 岗位需求生成请求
 */
export type PositionGenerateRequest = {
    /**
     * Description
     *
     * 岗位描述（一句话或详细说明）
     */
    description: string;
    /**
     * Documents
     *
     * 参考文档列表
     */
    documents?: Array<{
        [key: string]: string;
    }> | null;
};

/**
 * PositionListResponse
 *
 * 岗位列表项响应（简化版）
 */
export type PositionListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Title
     */
    title: string;
    /**
     * Department
     */
    department: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Application Count
     */
    application_count?: number;
};

/**
 * PositionResponse
 *
 * 岗位详情响应
 */
export type PositionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Title
     */
    title: string;
    /**
     * Department
     */
    department: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Required Skills
     */
    required_skills: Array<string>;
    /**
     * Optional Skills
     */
    optional_skills: Array<string>;
    /**
     * Min Experience
     */
    min_experience: number;
    /**
     * Education
     */
    education: Array<string>;
    /**
     * Salary Min
     */
    salary_min: number;
    /**
     * Salary Max
     */
    salary_max: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Application Count
     *
     * 申请数量
     */
    application_count?: number;
};

/**
 * PositionUpdate
 *
 * 更新岗位请求 - 所有字段可选
 */
export type PositionUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Required Skills
     */
    required_skills?: Array<string> | null;
    /**
     * Optional Skills
     */
    optional_skills?: Array<string> | null;
    /**
     * Min Experience
     */
    min_experience?: number | null;
    /**
     * Education
     */
    education?: Array<string> | null;
    /**
     * Salary Min
     */
    salary_min?: number | null;
    /**
     * Salary Max
     */
    salary_max?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * QAMessage
 *
 * 问答消息
 */
export type QaMessage = {
    /**
     * Seq
     *
     * 消息序号
     */
    seq: number;
    /**
     * Role
     *
     * 角色
     */
    role: 'interviewer' | 'candidate';
    /**
     * Content
     *
     * 内容
     */
    content: string;
    /**
     * Timestamp
     *
     * 时间戳
     */
    timestamp: string;
};

/**
 * QAMessageCreate
 *
 * 创建问答消息
 */
export type QaMessageCreate = {
    /**
     * Role
     *
     * 角色
     */
    role: 'interviewer' | 'candidate';
    /**
     * Content
     *
     * 内容
     */
    content: string;
};

/**
 * RandomResumeRequest
 *
 * 随机简历生成请求
 */
export type RandomResumeRequest = {
    /**
     * Position Id
     *
     * 岗位ID
     */
    position_id: string;
    /**
     * Count
     *
     * 生成数量
     */
    count?: number;
};

/**
 * ResponseModel[ApplicationDetailResponse]
 */
export type ResponseModelApplicationDetailResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ApplicationDetailResponse | null;
};

/**
 * ResponseModel[ApplicationResponse]
 */
export type ResponseModelApplicationResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ApplicationResponse | null;
};

/**
 * ResponseModel[BatchDeleteData]
 */
export type ResponseModelBatchDeleteData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: BatchDeleteData | null;
};

/**
 * ResponseModel[BatchHashCheckData]
 */
export type ResponseModelBatchHashCheckData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: BatchHashCheckData | null;
};

/**
 * ResponseModel[ComprehensiveAnalysisResponse]
 */
export type ResponseModelComprehensiveAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ComprehensiveAnalysisResponse | null;
};

/**
 * ResponseModel[FeedbackResponse]
 */
export type ResponseModelFeedbackResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: FeedbackResponse | null;
};

/**
 * ResponseModel[HashCheckData]
 */
export type ResponseModelHashCheckData = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: HashCheckData | null;
};

/**
 * ResponseModel[InterviewSessionResponse]
 */
export type ResponseModelInterviewSessionResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: InterviewSessionResponse | null;
};

/**
 * ResponseModel[PositionResponse]
 */
export type ResponseModelPositionResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: PositionResponse | null;
};

/**
 * ResponseModel[ResumeResponse]
 */
export type ResponseModelResumeResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ResumeResponse | null;
};

/**
 * ResponseModel[ScreeningTaskResponse]
 */
export type ResponseModelScreeningTaskResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: ScreeningTaskResponse | null;
};

/**
 * ResponseModel[VideoAnalysisResponse]
 */
export type ResponseModelVideoAnalysisResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Code
     */
    code?: number;
    /**
     * Message
     */
    message?: string;
    data?: VideoAnalysisResponse | null;
};

/**
 * ResumeCreate
 *
 * 创建简历请求
 */
export type ResumeCreate = {
    /**
     * Candidate Name
     *
     * 候选人姓名
     */
    candidate_name: string;
    /**
     * Phone
     *
     * 联系电话
     */
    phone?: string | null;
    /**
     * Email
     *
     * 电子邮箱
     */
    email?: string | null;
    /**
     * Content
     *
     * 简历内容
     */
    content: string;
    /**
     * Filename
     *
     * 原始文件名
     */
    filename?: string | null;
    /**
     * Notes
     *
     * 备注
     */
    notes?: string | null;
    /**
     * File Hash
     *
     * 文件哈希
     */
    file_hash: string;
    /**
     * File Size
     *
     * 文件大小
     */
    file_size?: number;
};

/**
 * ResumeListResponse
 *
 * 简历列表项响应（简化版）
 */
export type ResumeListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Candidate Name
     */
    candidate_name: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * Is Parsed
     */
    is_parsed: boolean;
    /**
     * Application Count
     */
    application_count?: number;
};

/**
 * ResumeResponse
 *
 * 简历详情响应
 */
export type ResumeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Candidate Name
     */
    candidate_name: string;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * File Hash
     */
    file_hash: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Is Parsed
     */
    is_parsed: boolean;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Application Count
     *
     * 申请数量
     */
    application_count?: number;
};

/**
 * ResumeUpdate
 *
 * 更新简历请求
 */
export type ResumeUpdate = {
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Parsed
     */
    is_parsed?: boolean | null;
};

/**
 * ScreeningResultUpdate
 *
 * 更新筛选结果请求
 */
export type ScreeningResultUpdate = {
    /**
     * Status
     *
     * 任务状态
     */
    status?: string | null;
    /**
     * Score
     *
     * 综合评分
     */
    score?: number | null;
    /**
     * 各维度评分
     */
    dimension_scores?: ScreeningScore | null;
    /**
     * Summary
     *
     * 筛选总结
     */
    summary?: string | null;
    /**
     * Recommendation
     *
     * 推荐结果
     */
    recommendation?: string | null;
    /**
     * Report Content
     *
     * 报告内容
     */
    report_content?: string | null;
    /**
     * Error Message
     *
     * 错误信息
     */
    error_message?: string | null;
};

/**
 * ScreeningScore
 *
 * 筛选评分详情
 */
export type ScreeningScore = {
    /**
     * Comprehensive Score
     *
     * 综合评分
     */
    comprehensive_score?: number | null;
    /**
     * Hr Score
     *
     * HR评分
     */
    hr_score?: number | null;
    /**
     * Technical Score
     *
     * 技术评分
     */
    technical_score?: number | null;
    /**
     * Manager Score
     *
     * 管理评分
     */
    manager_score?: number | null;
};

/**
 * ScreeningStartRequest
 *
 * 简历筛选启动请求
 */
export type ScreeningStartRequest = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ScreeningTaskBrief
 *
 * 筛选任务简要信息
 */
export type ScreeningTaskBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Score
     */
    score: number | null;
    /**
     * Recommendation
     */
    recommendation: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ScreeningTaskCreate
 *
 * 创建筛选任务请求
 */
export type ScreeningTaskCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
};

/**
 * ScreeningTaskResponse
 *
 * 筛选任务响应
 */
export type ScreeningTaskResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Score
     */
    score: number | null;
    dimension_scores?: ScreeningScore | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Recommendation
     */
    recommendation: string | null;
    /**
     * Report Content
     */
    report_content: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
    /**
     * Resume Content
     */
    resume_content?: string | null;
};

/**
 * SimulateCandidateAnswerRequest
 *
 * 模拟候选人回答请求
 */
export type SimulateCandidateAnswerRequest = {
    /**
     * Session Id
     *
     * 面试会话ID
     */
    session_id: string;
    /**
     * Question
     *
     * 面试官提问
     */
    question: string;
    /**
     * Candidate Type
     *
     * 候选人类型: ideal/junior/nervous/overconfident
     */
    candidate_type: string;
    /**
     * Conversation History
     *
     * 对话历史
     */
    conversation_history?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoAnalysisBrief
 *
 * 视频分析简要信息
 */
export type VideoAnalysisBrief = {
    /**
     * Id
     */
    id: string;
    /**
     * Video Name
     */
    video_name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Final Score
     */
    final_score?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * VideoAnalysisCreate
 *
 * 创建视频分析请求
 */
export type VideoAnalysisCreate = {
    /**
     * Application Id
     *
     * 应聘申请ID
     */
    application_id: string;
    /**
     * Video Name
     *
     * 视频名称
     */
    video_name: string;
    /**
     * Video Path
     *
     * 视频存储路径
     */
    video_path?: string | null;
    /**
     * File Size
     *
     * 文件大小
     */
    file_size?: number;
    /**
     * Duration
     *
     * 视频时长(秒)
     */
    duration?: number;
};

/**
 * VideoAnalysisResponse
 *
 * 视频分析响应
 */
export type VideoAnalysisResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Video Name
     */
    video_name: string;
    /**
     * Video Path
     */
    video_path: string | null;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Duration
     */
    duration: number;
    /**
     * Status
     */
    status: string;
    /**
     * Error Message
     */
    error_message: string | null;
    big_five_scores?: BigFiveScores | null;
    /**
     * Confidence Score
     */
    confidence_score: number | null;
    /**
     * Fraud Score
     */
    fraud_score: number | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Candidate Name
     */
    candidate_name?: string | null;
    /**
     * Position Title
     */
    position_title?: string | null;
};

/**
 * VideoResultUpdate
 *
 * 更新视频分析结果请求
 */
export type VideoResultUpdate = {
    /**
     * Status
     *
     * 分析状态
     */
    status?: string | null;
    /**
     * Error Message
     *
     * 错误信息
     */
    error_message?: string | null;
    /**
     * Openness
     */
    openness?: number | null;
    /**
     * Conscientiousness
     */
    conscientiousness?: number | null;
    /**
     * Extraversion
     */
    extraversion?: number | null;
    /**
     * Agreeableness
     */
    agreeableness?: number | null;
    /**
     * Neuroticism
     */
    neuroticism?: number | null;
    /**
     * Confidence Score
     */
    confidence_score?: number | null;
    /**
     * Fraud Score
     */
    fraud_score?: number | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Raw Result
     */
    raw_result?: {
        [key: string]: unknown;
    } | null;
};

export type GetPositionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Is Active
         *
         * 是否启用
         */
        is_active?: boolean | null;
    };
    url: '/api/v1/positions';
};

export type GetPositionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPositionsError = GetPositionsErrors[keyof GetPositionsErrors];

export type GetPositionsResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelPositionListResponse;
};

export type GetPositionsResponse = GetPositionsResponses[keyof GetPositionsResponses];

export type CreatePositionData = {
    body: PositionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/positions';
};

export type CreatePositionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePositionError = CreatePositionErrors[keyof CreatePositionErrors];

export type CreatePositionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPositionResponse;
};

export type CreatePositionResponse = CreatePositionResponses[keyof CreatePositionResponses];

export type DeletePositionData = {
    body?: never;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type DeletePositionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePositionError = DeletePositionErrors[keyof DeletePositionErrors];

export type DeletePositionResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeletePositionResponse = DeletePositionResponses[keyof DeletePositionResponses];

export type GetPositionData = {
    body?: never;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type GetPositionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPositionError = GetPositionErrors[keyof GetPositionErrors];

export type GetPositionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPositionResponse;
};

export type GetPositionResponse = GetPositionResponses[keyof GetPositionResponses];

export type UpdatePositionData = {
    body: PositionUpdate;
    path: {
        /**
         * Position Id
         */
        position_id: string;
    };
    query?: never;
    url: '/api/v1/positions/{position_id}';
};

export type UpdatePositionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePositionError = UpdatePositionErrors[keyof UpdatePositionErrors];

export type UpdatePositionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelPositionResponse;
};

export type UpdatePositionResponse = UpdatePositionResponses[keyof UpdatePositionResponses];

export type GetResumesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Keyword
         *
         * 搜索关键词(姓名)
         */
        keyword?: string | null;
    };
    url: '/api/v1/resumes';
};

export type GetResumesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResumesError = GetResumesErrors[keyof GetResumesErrors];

export type GetResumesResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelResumeListResponse;
};

export type GetResumesResponse = GetResumesResponses[keyof GetResumesResponses];

export type CreateResumeData = {
    body: ResumeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/resumes';
};

export type CreateResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResumeError = CreateResumeErrors[keyof CreateResumeErrors];

export type CreateResumeResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelResumeResponse;
};

export type CreateResumeResponse = CreateResumeResponses[keyof CreateResumeResponses];

export type CheckHashData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File Hash
         *
         * 文件哈希值
         */
        file_hash: string;
    };
    url: '/api/v1/resumes/check-hash';
};

export type CheckHashErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckHashError = CheckHashErrors[keyof CheckHashErrors];

export type CheckHashResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelHashCheckData;
};

export type CheckHashResponse = CheckHashResponses[keyof CheckHashResponses];

export type DeleteResumeData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type DeleteResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteResumeError = DeleteResumeErrors[keyof DeleteResumeErrors];

export type DeleteResumeResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteResumeResponse = DeleteResumeResponses[keyof DeleteResumeResponses];

export type GetResumeData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type GetResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResumeError = GetResumeErrors[keyof GetResumeErrors];

export type GetResumeResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelResumeResponse;
};

export type GetResumeResponse = GetResumeResponses[keyof GetResumeResponses];

export type UpdateResumeData = {
    body: ResumeUpdate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type UpdateResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateResumeError = UpdateResumeErrors[keyof UpdateResumeErrors];

export type UpdateResumeResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelResumeResponse;
};

export type UpdateResumeResponse = UpdateResumeResponses[keyof UpdateResumeResponses];

export type BatchDeleteResumesData = {
    body: BatchDeleteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/resumes/batch-delete';
};

export type BatchDeleteResumesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BatchDeleteResumesError = BatchDeleteResumesErrors[keyof BatchDeleteResumesErrors];

export type BatchDeleteResumesResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelBatchDeleteData;
};

export type BatchDeleteResumesResponse = BatchDeleteResumesResponses[keyof BatchDeleteResumesResponses];

export type CheckHashesData = {
    body: CheckHashesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/resumes/check-hashes';
};

export type CheckHashesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckHashesError = CheckHashesErrors[keyof CheckHashesErrors];

export type CheckHashesResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelBatchHashCheckData;
};

export type CheckHashesResponse = CheckHashesResponses[keyof CheckHashesResponses];

export type GetApplicationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Position Id
         *
         * 岗位ID筛选
         */
        position_id?: string | null;
        /**
         * Resume Id
         *
         * 简历ID筛选
         */
        resume_id?: string | null;
        /**
         * Include Details
         *
         * 是否返回完整详情（含所有关联数据）
         */
        include_details?: boolean;
    };
    url: '/api/v1/applications';
};

export type GetApplicationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApplicationsError = GetApplicationsErrors[keyof GetApplicationsErrors];

export type GetApplicationsResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelApplicationDetailResponse;
};

export type GetApplicationsResponse = GetApplicationsResponses[keyof GetApplicationsResponses];

export type CreateApplicationData = {
    body: ApplicationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/applications';
};

export type CreateApplicationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApplicationError = CreateApplicationErrors[keyof CreateApplicationErrors];

export type CreateApplicationResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelApplicationResponse;
};

export type CreateApplicationResponse = CreateApplicationResponses[keyof CreateApplicationResponses];

export type GetStatsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/applications/stats/overview';
};

export type GetStatsOverviewResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetStatsOverviewResponse = GetStatsOverviewResponses[keyof GetStatsOverviewResponses];

export type DeleteApplicationData = {
    body?: never;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_id}';
};

export type DeleteApplicationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApplicationError = DeleteApplicationErrors[keyof DeleteApplicationErrors];

export type DeleteApplicationResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteApplicationResponse = DeleteApplicationResponses[keyof DeleteApplicationResponses];

export type GetApplicationData = {
    body?: never;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_id}';
};

export type GetApplicationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApplicationError = GetApplicationErrors[keyof GetApplicationErrors];

export type GetApplicationResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelApplicationDetailResponse;
};

export type GetApplicationResponse = GetApplicationResponses[keyof GetApplicationResponses];

export type UpdateApplicationData = {
    body: ApplicationUpdate;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/applications/{application_id}';
};

export type UpdateApplicationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateApplicationError = UpdateApplicationErrors[keyof UpdateApplicationErrors];

export type UpdateApplicationResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelApplicationResponse;
};

export type UpdateApplicationResponse = UpdateApplicationResponses[keyof UpdateApplicationResponses];

export type GetScreeningTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
        /**
         * Status
         *
         * 状态筛选
         */
        status?: string | null;
    };
    url: '/api/v1/screening';
};

export type GetScreeningTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreeningTasksError = GetScreeningTasksErrors[keyof GetScreeningTasksErrors];

export type GetScreeningTasksResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelScreeningTaskResponse;
};

export type GetScreeningTasksResponse = GetScreeningTasksResponses[keyof GetScreeningTasksResponses];

export type CreateScreeningTaskData = {
    body: ScreeningTaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/screening';
};

export type CreateScreeningTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScreeningTaskError = CreateScreeningTaskErrors[keyof CreateScreeningTaskErrors];

export type CreateScreeningTaskResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelScreeningTaskResponse;
};

export type CreateScreeningTaskResponse = CreateScreeningTaskResponses[keyof CreateScreeningTaskResponses];

export type DeleteScreeningTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}';
};

export type DeleteScreeningTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScreeningTaskError = DeleteScreeningTaskErrors[keyof DeleteScreeningTaskErrors];

export type DeleteScreeningTaskResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteScreeningTaskResponse = DeleteScreeningTaskResponses[keyof DeleteScreeningTaskResponses];

export type GetScreeningTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}';
};

export type GetScreeningTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreeningTaskError = GetScreeningTaskErrors[keyof GetScreeningTaskErrors];

export type GetScreeningTaskResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelScreeningTaskResponse;
};

export type GetScreeningTaskResponse = GetScreeningTaskResponses[keyof GetScreeningTaskResponses];

export type UpdateScreeningResultData = {
    body: ScreeningResultUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}';
};

export type UpdateScreeningResultErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScreeningResultError = UpdateScreeningResultErrors[keyof UpdateScreeningResultErrors];

export type UpdateScreeningResultResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelScreeningTaskResponse;
};

export type UpdateScreeningResultResponse = UpdateScreeningResultResponses[keyof UpdateScreeningResultResponses];

export type GetScreeningStatusData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}/status';
};

export type GetScreeningStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScreeningStatusError = GetScreeningStatusErrors[keyof GetScreeningStatusErrors];

export type GetScreeningStatusResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetScreeningStatusResponse = GetScreeningStatusResponses[keyof GetScreeningStatusResponses];

export type DownloadScreeningReportData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/screening/{task_id}/download';
};

export type DownloadScreeningReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadScreeningReportError = DownloadScreeningReportErrors[keyof DownloadScreeningReportErrors];

export type DownloadScreeningReportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetVideoAnalysesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
        /**
         * Status
         *
         * 状态筛选
         */
        status?: string | null;
    };
    url: '/api/v1/video';
};

export type GetVideoAnalysesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoAnalysesError = GetVideoAnalysesErrors[keyof GetVideoAnalysesErrors];

export type GetVideoAnalysesResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelVideoAnalysisResponse;
};

export type GetVideoAnalysesResponse = GetVideoAnalysesResponses[keyof GetVideoAnalysesResponses];

export type CreateVideoAnalysisData = {
    body: VideoAnalysisCreate;
    path?: never;
    query?: never;
    url: '/api/v1/video';
};

export type CreateVideoAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVideoAnalysisError = CreateVideoAnalysisErrors[keyof CreateVideoAnalysisErrors];

export type CreateVideoAnalysisResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelVideoAnalysisResponse;
};

export type CreateVideoAnalysisResponse = CreateVideoAnalysisResponses[keyof CreateVideoAnalysisResponses];

export type DeleteVideoAnalysisData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}';
};

export type DeleteVideoAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVideoAnalysisError = DeleteVideoAnalysisErrors[keyof DeleteVideoAnalysisErrors];

export type DeleteVideoAnalysisResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteVideoAnalysisResponse = DeleteVideoAnalysisResponses[keyof DeleteVideoAnalysisResponses];

export type GetVideoAnalysisData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}';
};

export type GetVideoAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoAnalysisError = GetVideoAnalysisErrors[keyof GetVideoAnalysisErrors];

export type GetVideoAnalysisResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelVideoAnalysisResponse;
};

export type GetVideoAnalysisResponse = GetVideoAnalysisResponses[keyof GetVideoAnalysisResponses];

export type UpdateVideoResultData = {
    body: VideoResultUpdate;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}';
};

export type UpdateVideoResultErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVideoResultError = UpdateVideoResultErrors[keyof UpdateVideoResultErrors];

export type UpdateVideoResultResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelVideoAnalysisResponse;
};

export type UpdateVideoResultResponse = UpdateVideoResultResponses[keyof UpdateVideoResultResponses];

export type GetVideoStatusData = {
    body?: never;
    path: {
        /**
         * Video Id
         */
        video_id: string;
    };
    query?: never;
    url: '/api/v1/video/{video_id}/status';
};

export type GetVideoStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVideoStatusError = GetVideoStatusErrors[keyof GetVideoStatusErrors];

export type GetVideoStatusResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetVideoStatusResponse = GetVideoStatusResponses[keyof GetVideoStatusResponses];

export type GetInterviewSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
    };
    url: '/api/v1/interview';
};

export type GetInterviewSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewSessionsError = GetInterviewSessionsErrors[keyof GetInterviewSessionsErrors];

export type GetInterviewSessionsResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelInterviewSessionResponse;
};

export type GetInterviewSessionsResponse = GetInterviewSessionsResponses[keyof GetInterviewSessionsResponses];

export type CreateInterviewSessionData = {
    body: InterviewSessionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/interview';
};

export type CreateInterviewSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInterviewSessionError = CreateInterviewSessionErrors[keyof CreateInterviewSessionErrors];

export type CreateInterviewSessionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type CreateInterviewSessionResponse = CreateInterviewSessionResponses[keyof CreateInterviewSessionResponses];

export type DeleteInterviewSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}';
};

export type DeleteInterviewSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteInterviewSessionError = DeleteInterviewSessionErrors[keyof DeleteInterviewSessionErrors];

export type DeleteInterviewSessionResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteInterviewSessionResponse = DeleteInterviewSessionResponses[keyof DeleteInterviewSessionResponses];

export type GetInterviewSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}';
};

export type GetInterviewSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInterviewSessionError = GetInterviewSessionErrors[keyof GetInterviewSessionErrors];

export type GetInterviewSessionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type GetInterviewSessionResponse = GetInterviewSessionResponses[keyof GetInterviewSessionResponses];

export type UpdateInterviewSessionData = {
    body: InterviewSessionUpdate;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}';
};

export type UpdateInterviewSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateInterviewSessionError = UpdateInterviewSessionErrors[keyof UpdateInterviewSessionErrors];

export type UpdateInterviewSessionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type UpdateInterviewSessionResponse = UpdateInterviewSessionResponses[keyof UpdateInterviewSessionResponses];

export type GenerateQuestionsData = {
    body: GenerateQuestionsRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}/questions';
};

export type GenerateQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateQuestionsError = GenerateQuestionsErrors[keyof GenerateQuestionsErrors];

export type GenerateQuestionsResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GenerateQuestionsResponse = GenerateQuestionsResponses[keyof GenerateQuestionsResponses];

export type SyncMessagesData = {
    body: MessagesSyncRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}/sync';
};

export type SyncMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SyncMessagesError = SyncMessagesErrors[keyof SyncMessagesErrors];

export type SyncMessagesResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type SyncMessagesResponse = SyncMessagesResponses[keyof SyncMessagesResponses];

export type CompleteSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/interview/{session_id}/complete';
};

export type CompleteSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteSessionError = CompleteSessionErrors[keyof CompleteSessionErrors];

export type CompleteSessionResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInterviewSessionResponse;
};

export type CompleteSessionResponse = CompleteSessionResponses[keyof CompleteSessionResponses];

export type GetAnalysesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number;
        /**
         * Application Id
         *
         * 应聘申请ID
         */
        application_id?: string | null;
        /**
         * Recommendation Level
         *
         * 推荐等级筛选
         */
        recommendation_level?: string | null;
    };
    url: '/api/v1/analysis';
};

export type GetAnalysesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysesError = GetAnalysesErrors[keyof GetAnalysesErrors];

export type GetAnalysesResponses = {
    /**
     * Successful Response
     */
    200: PagedResponseModelComprehensiveAnalysisResponse;
};

export type GetAnalysesResponse = GetAnalysesResponses[keyof GetAnalysesResponses];

export type CreateAnalysisData = {
    body: ComprehensiveAnalysisCreate;
    path?: never;
    query?: never;
    url: '/api/v1/analysis';
};

export type CreateAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisError = CreateAnalysisErrors[keyof CreateAnalysisErrors];

export type CreateAnalysisResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelComprehensiveAnalysisResponse;
};

export type CreateAnalysisResponse = CreateAnalysisResponses[keyof CreateAnalysisResponses];

export type DeleteAnalysisData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analysis/{analysis_id}';
};

export type DeleteAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisError = DeleteAnalysisErrors[keyof DeleteAnalysisErrors];

export type DeleteAnalysisResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteAnalysisResponse = DeleteAnalysisResponses[keyof DeleteAnalysisResponses];

export type GetAnalysisData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analysis/{analysis_id}';
};

export type GetAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisError = GetAnalysisErrors[keyof GetAnalysisErrors];

export type GetAnalysisResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelComprehensiveAnalysisResponse;
};

export type GetAnalysisResponse = GetAnalysisResponses[keyof GetAnalysisResponses];

export type UpdateAnalysisData = {
    body: ComprehensiveAnalysisUpdate;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analysis/{analysis_id}';
};

export type UpdateAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAnalysisError = UpdateAnalysisErrors[keyof UpdateAnalysisErrors];

export type UpdateAnalysisResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelComprehensiveAnalysisResponse;
};

export type UpdateAnalysisResponse = UpdateAnalysisResponses[keyof UpdateAnalysisResponses];

export type GetAiStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/status';
};

export type GetAiStatusResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GetAiStatusResponse = GetAiStatusResponses[keyof GetAiStatusResponses];

export type AiGeneratePositionData = {
    body: PositionGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/position/generate';
};

export type AiGeneratePositionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGeneratePositionError = AiGeneratePositionErrors[keyof AiGeneratePositionErrors];

export type AiGeneratePositionResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGeneratePositionResponse = AiGeneratePositionResponses[keyof AiGeneratePositionResponses];

export type StartAiScreeningData = {
    body: ScreeningStartRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/screening/start';
};

export type StartAiScreeningErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartAiScreeningError = StartAiScreeningErrors[keyof StartAiScreeningErrors];

export type StartAiScreeningResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type StartAiScreeningResponse = StartAiScreeningResponses[keyof StartAiScreeningResponses];

export type AiGenerateInitialQuestionsData = {
    body: InterviewQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/initial-questions';
};

export type AiGenerateInitialQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGenerateInitialQuestionsError = AiGenerateInitialQuestionsErrors[keyof AiGenerateInitialQuestionsErrors];

export type AiGenerateInitialQuestionsResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGenerateInitialQuestionsResponse = AiGenerateInitialQuestionsResponses[keyof AiGenerateInitialQuestionsResponses];

export type AiGenerateAdaptiveQuestionsData = {
    body: CandidateQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/adaptive-questions';
};

export type AiGenerateAdaptiveQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGenerateAdaptiveQuestionsError = AiGenerateAdaptiveQuestionsErrors[keyof AiGenerateAdaptiveQuestionsErrors];

export type AiGenerateAdaptiveQuestionsResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGenerateAdaptiveQuestionsResponse = AiGenerateAdaptiveQuestionsResponses[keyof AiGenerateAdaptiveQuestionsResponses];

export type AiSimulateCandidateAnswerData = {
    body: SimulateCandidateAnswerRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/simulate-answer';
};

export type AiSimulateCandidateAnswerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiSimulateCandidateAnswerError = AiSimulateCandidateAnswerErrors[keyof AiSimulateCandidateAnswerErrors];

export type AiSimulateCandidateAnswerResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiSimulateCandidateAnswerResponse = AiSimulateCandidateAnswerResponses[keyof AiSimulateCandidateAnswerResponses];

export type AiGenerateReportData = {
    body: FinalReportRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/interview/report';
};

export type AiGenerateReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGenerateReportError = AiGenerateReportErrors[keyof AiGenerateReportErrors];

export type AiGenerateReportResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiGenerateReportResponse = AiGenerateReportResponses[keyof AiGenerateReportResponses];

export type AiComprehensiveAnalysisData = {
    body: ComprehensiveAnalysisRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/analysis/comprehensive';
};

export type AiComprehensiveAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiComprehensiveAnalysisError = AiComprehensiveAnalysisErrors[keyof AiComprehensiveAnalysisErrors];

export type AiComprehensiveAnalysisResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type AiComprehensiveAnalysisResponse = AiComprehensiveAnalysisResponses[keyof AiComprehensiveAnalysisResponses];

export type GenerateRandomResumeData = {
    body: RandomResumeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/dev/random-resume';
};

export type GenerateRandomResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateRandomResumeError = GenerateRandomResumeErrors[keyof GenerateRandomResumeErrors];

export type GenerateRandomResumeResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type GenerateRandomResumeResponse = GenerateRandomResumeResponses[keyof GenerateRandomResumeResponses];

export type SubmitFeedbackData = {
    body: FeedbackRequest;
    path?: never;
    query?: {
        /**
         * Regenerate
         *
         * 是否重新生成报告
         */
        regenerate?: boolean;
    };
    url: '/api/v1/feedback';
};

export type SubmitFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitFeedbackError = SubmitFeedbackErrors[keyof SubmitFeedbackErrors];

export type SubmitFeedbackResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelFeedbackResponse;
};

export type SubmitFeedbackResponse = SubmitFeedbackResponses[keyof SubmitFeedbackResponses];

export type DeleteAllExperiencesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         *
         * 按类别清空，不填则清空全部
         */
        category?: string | null;
    };
    url: '/api/v1/feedback/experiences';
};

export type DeleteAllExperiencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAllExperiencesError = DeleteAllExperiencesErrors[keyof DeleteAllExperiencesErrors];

export type DeleteAllExperiencesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetExperiencesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         *
         * 按类别筛选
         */
        category?: string | null;
    };
    url: '/api/v1/feedback/experiences';
};

export type GetExperiencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExperiencesError = GetExperiencesErrors[keyof GetExperiencesErrors];

export type GetExperiencesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateExperienceData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Category
         *
         * 类别: screening/interview/analysis
         */
        category: string;
        /**
         * Learned Rule
         *
         * 经验规则
         */
        learned_rule: string;
        /**
         * Context Summary
         *
         * 上下文摘要
         */
        context_summary?: string;
    };
    url: '/api/v1/feedback/experiences';
};

export type CreateExperienceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateExperienceError = CreateExperienceErrors[keyof CreateExperienceErrors];

export type CreateExperienceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteExperienceData = {
    body?: never;
    path: {
        /**
         * Experience Id
         */
        experience_id: string;
    };
    query?: never;
    url: '/api/v1/feedback/experiences/{experience_id}';
};

export type DeleteExperienceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteExperienceError = DeleteExperienceErrors[keyof DeleteExperienceErrors];

export type DeleteExperienceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: DictResponse;
};

export type RootResponse = RootResponses[keyof RootResponses];
